name: outwork
description: Outwork all of them
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0+29

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.17.4
  animated_text_kit: ^4.2.2
  image_cropper: ^6.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  syncfusion_flutter_sliders: ^25.2.5
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  syncfusion_flutter_gauges: ^25.2.5
  step_progress_indicator: ^1.0.2
  sleek_circular_slider: ^2.0.1
  firebase_storage: ^11.5.6
  adaptive_dialog: ^2.0.0
  syncfusion_flutter_datepicker: ^25.2.5
  uuid: ^4.2.2
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^25.2.5
  percent_indicator: ^4.2.3
  badges: ^3.1.2
  settings_ui: ^2.0.2
  circular_countdown_timer: ^0.2.3
  persistent_bottom_nav_bar: ^5.0.2
  numberpicker: ^2.1.2
  audioplayers: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  awesome_snackbar_content: ^0.1.1
  line_icons: ^2.0.3
  flutter_dotenv: ^5.1.0
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  custom_refresh_indicator: ^3.0.0
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  rxdart: ^0.27.7
  animated_flip_counter: ^0.3.4
  introduction_screen: ^3.1.14
  purchases_flutter: ^6.25.0
  in_app_update: ^4.2.2
  smooth_page_indicator: ^1.1.0
  time_machine: ^0.9.17
  jiffy: ^6.2.1
  google_mobile_ads: ^5.1.0
  awesome_notifications: ^0.9.3+1
  the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.4.0

#dependency_overrides:
#  intl: ^0.18.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#000000"


flutter_native_splash:
  color: "#000000"
  image: assets/logo_foreground.png
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: assets/logo_foreground.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/streaks/
    - assets/emojis/
    - assets/emojis/dailycheckin/
    - assets/
    - assets/bad habits/
    - .env

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
