name: outwork
description: Outwork all of them
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.13.3
  animated_text_kit: ^4.2.2
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  syncfusion_flutter_sliders: ^23.2.7
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  syncfusion_flutter_gauges: ^23.2.7
  step_progress_indicator: ^1.0.2
  sleek_circular_slider: ^2.0.1
  firebase_storage: ^11.5.6
  adaptive_dialog: ^2.0.0
  syncfusion_flutter_datepicker: ^23.2.7
  uuid: ^4.2.2
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^23.2.7
  percent_indicator: ^4.2.3
  badges: ^3.1.2
  settings_ui: ^2.0.2
  circular_countdown_timer: ^0.2.3
  persistent_bottom_nav_bar: ^5.0.2
  numberpicker: ^2.1.2
  audioplayers: ^5.2.1
  flutter_launcher_icons: ^0.13.1
  awesome_snackbar_content: ^0.1.3
  line_icons: ^2.0.3
  flutter_dotenv: ^5.1.0
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  custom_refresh_indicator: ^3.0.0
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  flutter_local_notifications: ^17.0.0
  rxdart: ^0.27.7
  animated_flip_counter: ^0.2.6
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#000000"



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/streaks/
    - assets/emojis/
    - assets/emojis/dailycheckin/
    - assets/
    - assets/bad habits/
    - .env

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
