name: outwork
description: Outwork all of them
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.13.3
  animated_text_kit: ^4.2.2
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  syncfusion_flutter_sliders: ^23.2.7
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  syncfusion_flutter_gauges: ^23.2.7
  step_progress_indicator: ^1.0.2
  sleek_circular_slider: ^2.0.1
  firebase_storage: ^11.5.6
  adaptive_dialog: ^2.0.0
  syncfusion_flutter_datepicker: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/emojis/

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
